# Default YAML values (more information on Jekyll's site)
defaults:
    scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true  # add comments to all blog posts
      share: true # add social media sharing buttons to all blog posts
      author_profile: true
      read_time: true
      related: true
      show_date: true      
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
      type: pages
    values:
      layout: single

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-feed

domain: guillaumeben.xyz
url: https://guillaumeben.xyz # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

title: "GuillaumeBen's Notebook"
name: "Guillaume B."
subtitle: "My small contribution to security"
url: https://guillaumeben.xyz
logo: "/assets/img/avatar-icon.png"
breadcrumbs: true  # disabled by default

author:
  name     : "Guillaume B."
  avatar   : "/assets/img/avatar-icon.png"
  bio      : "Security Analyst, Threat Hunter, Detection Engineering @ Microsoft."
  location : "Somewhere, Belgium"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tux_be"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tuxnam"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guillaume-benats-25550426/"
